apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: echoserver-instance
        image: echoserver:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080